drop table if exists member CASCADE;
create table member
(
    sno bigint generated by default as identity,
    id varchar(255),
    name varchar(255),
    pwd varchar(255),
    phone varchar(255),
    email varchar(255),
    regDt TIMESTAMP default CURRENT_TIMESTAMP,
    primary key (sno)
);

drop table if exists task CASCADE;
create table task
(
    sno bigint generated by default as identity,
    memberSno bigint,
    title varchar(255),
    content text,
    status enum('N', 'Y', 'E', 'C') default 'N',
    regDt TIMESTAMP default CURRENT_TIMESTAMP,
    modDt TIMESTAMP,
    primary key (sno)
);

drop table if exists log CASCADE;
create table log
(
    sno bigint generated by default as identity,
    taskSno bigint,
    type enum('member', 'task'),
    ip varchar(255),
    content text,
    regDt TIMESTAMP default CURRENT_TIMESTAMP,
    primary key (sno)
);